### ISSUE TITLE
Document workaround for not being able to download ClojureTools jar

### ISSUE THREAD

**Issue by borkdude** [borkdude/deps.clj#20]
There is an easy workaround: download the .jar file yourself and put it in ~/.deps.clj/ClojureTools 
It's part of this zip file: https://download.clojure.org/install/clojure-tools-1.10.1.507.zip

**Comment by lread** [comment]
Hiya @borkdude!  While working with deps.clj on GitHub Actions for Windows, I think I might have gotten this failure.

After a `deps -Sdescribe`, GitHub Actions output was:

```
Could not find clojure-tools-1.10.1.507.jar. Attempting download.
##[error]Process completed with exit code 1.
```

After using your workaround of pre-downloading ClojureTools things worked.  

But I wonder why this was necessary - and am happy to help fix.

**Comment by borkdude** [comment]
@lread deps.clj, like clojure / clj needs tools.jar to calculate the classpath etc. That's where the actual maven stuff happens.

See https://github.com/borkdude/deps.clj/blob/5d51b80176bdcb96927ce5e6aedb25581db0e2e0/src/borkdude/deps.clj#L208. 

There could be reasons why the download fails. One person reported a corporate proxy problem. I don't know why yours failed on Github. You can try this locally by removing ~/.deps.clj and re-invoking deps.clj.

**Comment by lread** [comment]
Thanks  for the reply @borkdude, much appreciated. 

It works fine for me locally on my Windows 10 VM, and worked once for me on GitHub Action Windows. I’ll do some digging to understand what is happening.

**Comment by lread** [comment]
After digging for the day, I can't say I understand why things failed on GitHub Actions on Windows for me.  I can consistently reproduce the failures up on GitHub, but had no luck reproducing them on my Windows 10 VM. 

My goal is to use `deps.exe` literally as `clojure`.

I can say that if I install `deps.exe` via `install.ps1` as per README, I can then easily rename it to `clojure.exe` and then things work for me.  I was previously installing `deps.exe` via scoop which made creating a clojure alias trickier, and that seems to have been a contributing factor to the failure I encountered.

**Comment by borkdude** [comment]
Are you still able to reproduce the failure? Do you have a link to a failing build?

**Comment by lread** [comment]
I initially experienced the problem on rewrite-cljc and tried to diagnose there a bit.  I even brought in a deps.exe with some println debugging, but I was struggling to gain an understand of the cause of the symptom within the context of a rewrite-cljc build.  

So I created a [repro repo](https://github.com/lread/repro-depsclj-fail-gha-win). Some notes:
- Although I do not understand the cause, when the symptom is triggered, it seems to be consistently repeatable.
- Oddly, [adding babashka triggered the symptom](https://github.com/lread/repro-depsclj-fail-gha-win/commit/6200b719c01894b4dc28ae461baa20a6447b0825).
- But if I initiated a `clojure -Sdescribe` (where clojure is really deps), before running bb, the symptom did not present.
- In the end, after failing to create a minimal scenario that triggered the symptom, [I changed the java version and, oddly, to me, the symptom triggered](https://github.com/lread/repro-depsclj-fail-gha-win/commit/0d9826a766b187b211d31fc7d5c07203d39922f5)

After that, even though I had no understanding of the cause, I figured I had enough clues of what not to do to carry on with rewrite-cljc. 
- I was not entirely confident in my technique of "aliasing" clojure->deps for a scoop installed deps.clj, so [I installed deps.clj via `install.ps1` and simply renamed deps.exe to clojure.exe](https://github.com/lread/rewrite-cljc-playground/blob/0b506a80f5021e7505bce2776aacf3cdcd51c7f8/.github/workflows/unit-test.yml#L85)
- [Ran `clojure -Sdescribe` (where clojure is really deps) early](https://github.com/lread/rewrite-cljc-playground/blob/0b506a80f5021e7505bce2776aacf3cdcd51c7f8/.github/workflows/unit-test.yml#L96).

Note rewrite-cljc links are on a WIP branch, I'll update them after I merge to master.

**Comment by borkdude** [comment]
> But if I initiated a clojure -Sdescribe (where clojure is really deps), before running bb, the symptom did not present.

That might be because clojure caches the classpath and in that case the downloaded clojure tools jar is not needed?

Could it be a permission issue where the downloaded jar file can't be installed in the `~/.deps.clj` directory?
Can you forcible return exit code 0 with `deps.exe -Sdescribe || true` (the powershell equivalent thereof) and then do `ls ~/.deps.clj` (the powershell equivalent thereof)?

**Comment by lread** [comment]
I'm beginning to suspect the failure is somehow related to how I aliased deps to clojure when installing from scoop.  If it is just me not understanding how to properly use Windows, maybe not worth digging into anymore. 

Here's a GitHub Actions matrix that installs [from scoop](https://github.com/lread/repro-depsclj-fail-gha-win/blob/98e043305c3034e16131d17f5559a447895f7b54/.github/workflows/win-test.yml#L29-L36) and [from script](https://github.com/lread/repro-depsclj-fail-gha-win/blob/98e043305c3034e16131d17f5559a447895f7b54/.github/workflows/win-test.yml#L38-L43).  

Both alias deps to clojure. I use the term alias as the intended result and not a technique.

[The script variation passes and the scoop variation fails](https://github.com/lread/repro-depsclj-fail-gha-win/runs/925378050?check_suite_focus=true).

**Comment by borkdude** [comment]
@lread What happens when you install with scoop and don't rename deps.exe?

**Comment by lread** [comment]
I do like your tenacity! 🙂 

[A scoop install with with a call to deps.exe instead of the clojure alias passes](https://github.com/lread/repro-depsclj-fail-gha-win/runs/927668741?check_suite_focus=true).

**Comment by lread** [comment]
I do remember a case where calling deps.exe failed with the same symptoms.  I'll see if I can reproduce that one.

**Comment by lread** [comment]
Ok, without any clojure "aliasing", [I can get a scoop installed deps to fail if I call it in the same GitHub Action step as scoop installation](https://github.com/lread/repro-depsclj-fail-gha-win/runs/927801349?check_suite_focus=true).

If I repeat the above, but scoop install deps.clj with the `--independent` option, the symptom does not manifest.

I started using `--independent` when installing via scoop because I guessed that GitHub Actions on Windows already had what was required.  A `scoop install deps.clj` succeeds, but does show some suspicious output `ERROR` output on GitHub Actions when installing the `vcredist2015` scoop dependency:

```
Installing 'vcredist2015' (14.0.24215) [64bit]
Downloading https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x64.exe (14.6 MB)...
Checking hash of vc_redist.x64.exe ... ok.
Downloading https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe (13.8 MB)...
Checking hash of vc_redist.x86.exe ... ok.
Linking ~\scoop\apps\vcredist2015\current => ~\scoop\apps\vcredist2015\14.0.24215
Running post-install script...
ERROR Exit code was 1638!
ERROR Exit code was 1638!
'vcredist2015' (14.0.24215) was installed successfully!
Notes
-----
You can now remove this installer with 'scoop uninstall vcredist2015'
Installing 'deps.clj' (0.0.9) [64bit]
Downloading https://github.com/borkdude/deps.clj/releases/download/v0.0.9/deps.clj-0.0.9-windows-amd64.zip (9.0 MB)...
Checking hash of deps.clj-0.0.9-windows-amd64.zip ... ok.
Extracting deps.clj-0.0.9-windows-amd64.zip ... done.
Linking ~\scoop\apps\deps.clj\current => ~\scoop\apps\deps.clj\0.0.9
Creating shim for 'deps'.
'deps.clj' (0.0.9) was installed successfully!
```
If I repeat the above test [and run deps in a separate GitHub Action step, things work](https://github.com/lread/repro-depsclj-fail-gha-win/runs/927863868?check_suite_focus=true).  

Note that each GitHub Action step runs in a separate process. Environment must be explicitly shared between steps.  So I expect something from the vcredist2015 install negatively affected deps.exe but that negative effect was not preserved for the next step.

I'll try dumping the environment for and see if that gives me some more clues.

**Comment by lread** [comment]
After dumping and comparing environment variables, powershell aliases, and some dir trees, I'm not seeing anything obvious that would trigger the failure.

It seems that the exit code 1638 on scoop dependency of vcredist2015 that I showed above [means a newer version is already installed](https://support.microsoft.com/en-ca/help/4092997/vc-2015-redistributable-install-error-1638-when-newer-version-present).  I have since, somehow managed to trigger failures regardless of whether or not scoop deps are included.

An interesting new thing: if I scoop install deps.clj and then don't run `deps.exe` at all, but instead run `java -version` I get one line of output from java, then an exit:

```
openjdk version "1.8.0_262"
##[error]Process completed with exit code 1.
```

A prior step output of `java -version` is 3 lines:
```
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (Zulu 8.48.0.51-CA-win64) (build 1.8.0_262-b19)
OpenJDK 64-Bit Server VM (Zulu 8.48.0.51-CA-win64) (build 25.262-b19, mixed mode)
```

It almost feels like GitHub Actions is truncating the output. 

I ask myself if I am hitting a problem with scoop, deps.clj, PowerShell, GitHub Actions on Windows and/or some blind spot I don't see in my tests.

What seems to be reliable a work-around for deps.clj in GitHub Actions on Windows is:
1. Install deps.clj via `install.ps1` or scoop
2. In the next step bring down ClojureTools via `deps -Sdescribe`

If you want to treat deps.exe as clojure.exe:
1. install deps.clj via `install.ps1`
2. `Rename-Item $HOME\deps.clj\deps.exe clojure.exe`
3. In the next step bring down ClojureTools via `deps -Sdescribe`

That's it for me for now, I think I'll take a nap. 🙂

**Comment by borkdude** [comment]
The error messages should be pretty self-explanatory now.
